repos:
  # 格式化代码（black）
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  # 自动排序 imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # 类型检查（mypy）
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
        args: []

  # 代码风格检查（ruff，支持 flake8/pylint/radon 等）
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff

  # 检查测试是否通过
  - repo: local
    hooks:
      - id: run-all-chapter-tests
        name: Run all chapter tests
        entry: python3 scripts/run_all_tests.py
        language: system
        types: [python]

  # 通用的文本检查器（行尾空格、换行符等）
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
