[project]
name = "PyMico"
version = "0.1.0"
description = "Use FastApi to build python microservices"
authors = [{ name = "Rem", email = "yl16221218@163.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "uvicorn[standard]"
]